version: "2"
services:
  node:
    container_name: iota-devnet-courier
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8084:8080"
    command: "npm start"
